config/routes.rb
CulturalGps::Application.routes.draw do
  devise_for :admins
  root 'events#index'

  resources :events
  resources :places
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :place

  validates :name, presence: true, length: { maximum: 80 }
  validates :description, presence: true, length: { maximum: 300 }

  attr_accessor :bearing, :distance

  scope :order_by_start_date, -> (order = 'ASC') { order("events.start_date #{order}") }
  scope :doesnt_end, -> () { where('events.end_date >= ?', Time.zone.now) }
  scope :until_date, -> (date = Time.zone.now.at_end_of_quarter) {
    where("events.end_date <= ?", date)
  }
  scope :get_future_events, -> () { doesnt_end.until_date.order_by_start_date }

  def self.start_until_tomorrow
    where("start_date <= ?", Date.today + 1.days)
  end

  def get_bearings(location)
    place.bearing_to(location) if place.geocoded?
  end

  def get_distance(location)
    place.distance_to(location) if place.geocoded?
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :events

  scope :search_name, ->(q) { where('places.name ILIKE ?', "%#{q}%") }

  validates :name, presence: true, uniqueness: true, length: { maximum: 80 }
  validates :description, length: { maximum: 300 }
  validates :longitude, presence: true
  validates :latitude, presence: true

  reverse_geocoded_by :latitude, :longitude, :address => :location
  after_validation :reverse_geocode

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def decorators
    @memoized ||= CollectDecorator.new
  end

  helper_method :decorators

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, :except => [:index, :show]

  expose(:events)
  expose(:future_events, model: :event) { events.get_future_events }
  expose(:event)
  expose(:geo_location) { [ params[:latitude], params[:longitude] ] }

  def index
    future_events.includes(:place).limit(30)
    @useCurrentPosition = params[:useCurrentPosition] || false
  end

  def show; end

  def new
    @event = Event.new
  end

  def edit; end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description, :start_date, :end_date, :place_id)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]

  expose(:places)
  expose(:place, attributes: :place_params)

  has_scope :search_name, as: :q

  def index; end
  def show; end
  def new; end
  def edit; end

  def create
    respond_to do |format|
      if place.save
        format.html { redirect_to place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: place }
      else
        format.html { render action: 'new' }
        format.json { render json: place.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if place.update(place_params)
        format.html { redirect_to place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: place.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def isLogged?
    current_admin or current_user
  end

  def is_active?(page_name)
    "active" if params[:controller] == page_name
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def get_event_time(date)
    return nil if date.nil?
    return get_event_hour(date) if date.today?
    return time_ago_in_words(date) if DateTime.now + 24.hour <= date
    get_event_date(date)
  end

  def get_event_date(date)
    date.strftime('%d-%m-%Y')
  end

  def get_hour(time)
    time.strftime('%H:%M')
  end

  def get_event_hour(time)
    "today at #{get_hour(time)}"
  end

  def normalize_distance(bearing)
    distance = number_to_human(bearing, units: {centi: "cm", unit: "m", thousand: "km"})
  end

  def place_direction(bearing)
    Geocoder::Calculations.compass_point( bearing - 180 )
  end

  def place_direction_class(bearing)
    case place_direction(bearing)
    when 'N'; 'icon-arrow-up'
    when 'S'; 'icon-arrow-down'
    when 'W'; 'icon-arrow-left'
    when 'E'; 'icon-arrow-right'
    end
  end

  def has_started_class(start_date)
    'active' if start_date <= Time.now
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <div class="panel-body">
    <% if @event.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <p><strong><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</strong></p>

        <p>
        <% @event.errors.full_messages.each do |msg| %>
          <%= msg %> <br>
        <% end %>
        </p>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :start_date %><br>
      <%= f.datetime_select :start_date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :end_date %><br>
      <%= f.datetime_select :end_date, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :place_id %><br>
      <%= f.text_field :place_id, data: { url: places_path(format: :json), value: ( @event.new_record? )? '' : @event.place.name } %>
    </div>
  </div>

  <div class="panel-footer">
    <%= f.submit 'Create', class: 'btn btn-primary' %>

    <% unless @event.new_record? %>
      <%= link_to 'Show', @event, class: 'btn btn-default' %>
      <%= link_to 'Back', events_path, class: 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Editing event</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col-sm-12 col-xs-12 col-md-12">
    <%= form_tag(root_path, method: "get") do %>
      <%= hidden_field_tag(:latitude) %>
      <%= hidden_field_tag(:longitude) %>
      <%= check_box_tag(:useCurrentPosition, true, @useCurrentPosition) %>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          Upcoming events
          <% if current_admin %>
            <%= link_to 'New Event', new_event_path, class: "btn btn-primary pull-right" %>
          <% end %>
          <button id="useCurrentPosition_button" class="btn btn-success pull-right <%= 'active' if @useCurrentPosition %>" disabled>
            Use my position &nbsp;
            <i class="icon-compass"></i>
          </button>
        </h3>
      </div>
      <div class="panel-body">
        <p>
          All upcoming events are displayed here, also they displays:
          event name, location in black label and time
        </p>
        <p>
          You may use your current position <span class="label label-success">(the green button)</span>, the
          app show you the direction to event <strong>(N, S, E, W)</strong>
        </p>
      </div>
      <% if future_events.any? %>
        <table class="table table-condensed table-striped" id="event-table">
          <tbody>
            <% future_events.each do |event| %>
              <tr data-link="<%= event_url(event) %>" class="<%= has_started_class(event.start_date) %>">
                <td>
                  <h4><%= event.name %></h4>
                  <strong>
                    <i class="icon-location"></i> <%= event.place.name %>
                  </strong> <br>
                  <p>
                    <i class="icon-calendar"></i>
                    Start <%= get_event_time event.start_date %> and
                    End <%= get_event_time event.end_date %>
                  </p>
                </td>
                <% if @useCurrentPosition %>
                  <td class="location-distance"><%= normalize_distance event.get_distance(geo_location) %></td>
                  <td class="arrow-direction">
                    <i class="<%= place_direction_class event.get_bearings(geo_location) %>"></i>
                  </td>
                <% end %>
                <% if current_admin %>
                  <td class="actions">
                      <%= link_to 'Edit', edit_event_path(event), class: 'btn btn-primary' %>
                      <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <div class="alert alert-info">Not upcoming events yet. Try later</div>
      <% end %>
  </div>

  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">New Event</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"><%= @event.name %></h1>
  </div>
  <div class="panel-body">
    <p>
      <%= @event.description %>
    </p>
    <address>
      Where? <strong><%= @event.place.name %></strong> <br>
      <%= @event.place.location %>
    </address>
    <p>
      <strong>Start at:</strong>
      <%= @event.start_date %>
    </p>

    <p>
      <strong>End at:</strong>
      <%= @event.end_date %>
    </p>

    <div id="map-image" data-latitude="<%= @event.place.latitude %>" data-longitude="<%= @event.place.longitude %>">
      <img src="" alt="">
    </div>
  </div>
  <div class="panel-footer">
    <% if isLogged? %>
      <%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-primary' %>
    <% end %>
    <%= link_to 'Back', events_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CulturalGps</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <%= favicon_link_tag 'favicon.png' %>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'partials/base/nav' %>

<div class="container">
  <%= yield %>
</div>

<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
<%= javascript_include_tag "application" %>
</body>
</html>

app/views/partials/base/_nav.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= link_to 'Cultural GPS', root_path, class: 'navbar-brand' %></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= is_active? 'places' %>"><%= link_to 'Places', places_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_admin %>
          <li class="navbar-text">Signed in as <%= current_admin.email %></li>
          <li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', admin_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/places/_form.html.erb
<%= form_for(place) do |f| %>
  <div class="panel-body">

    <% if place.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

        <ul>
        <% place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :latitude, "data-geo"=>"lat", class: 'form-control' %>
    <%= f.hidden_field :longitude, "data-geo"=>"lng", class: 'form-control' %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :location %><br>
      <%= f.text_field :location, "data-geocomplete"=>"", class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div id="map-canvas"></div>
  </div>

  <div class="panel-footer">
    <%= f.submit 'Create', class: 'btn btn-primary' %>

    <% unless place.new_record? %>
      <%= link_to 'Show', place, class: 'btn btn-default' %>
      <%= link_to 'Back', events_path, class: 'btn btn-default' %>
    <% end %>
  </div>
<% end %>

app/views/places/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Direction</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.description %></td>
        <td><%= place.location %></td>
        <td>
          <%= link_to 'Show', place %>
          <% if current_admin %>
            <%= link_to 'Edit', edit_place_path(place) %>
            <%= link_to 'Destroy', place_path(place), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/places/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Editing Place</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/places/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>
      Listing places
      <% if current_admin %>
        <%= link_to 'New Place', new_place_path, class: 'btn btn-primary pull-right' %>
      <% end %>
    </h1>
  </div>
  <%= render 'list' %>
</div>

app/views/places/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">New Place</h1>
  </div>
  <%= render 'form' %>
</div>

app/views/places/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div id="map-image" data-size="300px" data-latitude="<%= place.latitude %>"
         data-longitude="<%= place.longitude %>">
      <img src="" alt="<%= place.name %>" class="pull-right">
    </div>
    <p>
      <strong>Name:</strong>
      <%= place.name %>
    </p>

    <p>
      <strong>Location</strong>
      <%= place.location %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= place.description %>
    </p>
  </div>
  <br>
  <div class="panel-footer">
    <% if current_admin %>
      <%= link_to 'Edit', edit_place_path(place), class: 'btn btn-primary' %>
    <% end %>
      <%= link_to 'Back', places_path, class: 'btn btn-default' %>
    </div>
</div>